## Importação das bibliotecas necessárias

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime



## Verificando as bases

Primeiramente, carregando as bases para objetos do tipo DataFrame para melhor manipulação e visualização dos dados

In [2]:
demographic = pd.read_csv('DemographicData_ZCTAs.csv')
geocode = pd.read_csv('df_geocode.csv')
economic = pd.read_csv('EconomicData_ZCTAs.csv')
test = pd.read_csv('test_data.csv')
transactional = pd.read_csv('transactional_data.csv')

Existe uma coluna com index desnecessária. A coluna Zipcode está como float, mas na verdade deve ser considerada uma string, pelo fato de estar funcionando como uma variável categórica nesse contexto
 

In [3]:
geocode.head()


Unnamed: 0 Lab Id                                            Address  \
0           0   L152      3800 PLEASANT HILL RD STE 1, DULUTH, GA 30096   
1           1   L520                    1614 N JAMES ST, ROME, NY 13440   
2           2   L141     12911 120TH AVE NE STE D60, KIRKLAND, WA 98034   
3           3   L524  5667 PEACHTREE DUNWOODY RD 250, ATLANTA, GA 30342   
4           4   L545                 1204 IL HWY 164, OQUAWKA, IL 61469   

                  Location  Zipcode  
0    34.000319,-84.1629724  30096.0  
1   43.2311327,-75.4445363  13440.0  
2  47.7162786,-122.1838152  98034.0  
3   33.9093875,-84.3529096  30342.0  
4   40.9309925,-90.9437598  61469.0

Existe uma coluna com index desnecessária. O conjunto de dados não segue o padrão tidy, está um pouco desorganizado

In [4]:
economic.head()


Unnamed: 0              id Geographic Area Name  \
0           0  8600000US35004          ZCTA5 35004   
1           1  8600000US35005          ZCTA5 35005   
2           2  8600000US35006          ZCTA5 35006   
3           3  8600000US35007          ZCTA5 35007   
4           4  8600000US35010          ZCTA5 35010   

   TotalHouseholds_LessThan$10.000  TotalHouseholds_$10.000to$14.999  \
0                              198                                71   
1                              188                               184   
2                               71                                20   
3                              396                               208   
4                              700                               610   

   TotalHouseholds_$15.000to$24.999  TotalHouseholds_$25.000to$34.999  \
0                               298                               513   
1                               318                               293   
2                               117                               104   
3                               670                               462   
4                              1093                               957   

   TotalHouseholds_$35.000to$49.999  TotalHouseholds_$50.000to$74.999  \
0                               647                              1117   
1                               353                               562   
2                               154                               176   
3                              1173                              1854   
4                              1056                              1512   

   TotalHouseholds_$75.000to$99.999  TotalHouseholds_$100.000to$149.999  \
0                               529                                 945   
1                               299                                 407   
2                               124                                 194   
3                              1578                                2224   
4                               807                                 749   

   TotalHouseholds_$150.000to$199.999  TotalHouseholds_$200.000OrMore  
0                                 245                              61  
1                                  67                              26  
2                                  51                               7  
3                                 473                             254  
4                                 254                             249

A principio tudo parace correto

In [5]:
test.head()


CodItem                                          Desc Item Category  \
0  70003237  MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...       CA   
1  70000638                    HEMOGRAMA, AUTOMATIZADO, SANGUE       CA   
2  70001597                                    FERRITINA, SORO       CA   
3  70000103  FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...       CA   
4  70000224  CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...       CA   

    Family     Speciality  Testing Cost  
0  CORELAB   BIOCHEMISTRY          1.78  
1   HEMATO    BLOOD COUNT          2.46  
2  CORELAB  IMMUNOHORMONE          2.11  
3  CORELAB   BIOCHEMISTRY          0.80  
4  CORELAB   BIOCHEMISTRY          1.02

Existe uma coluna com index desnecessária. O conjunto de dados não segue o padrão tidy, está um pouco desorganizado


In [6]:
demographic.head()


Unnamed: 0              Id GeographicAreaName  TotalPopulation  \
0           0  8600000US35004        ZCTA5 35004            12045   
1           1  8600000US35005        ZCTA5 35005             7344   
2           2  8600000US35006        ZCTA5 35006             2883   
3           3  8600000US35007        ZCTA5 35007            26332   
4           4  8600000US35010        ZCTA5 35010            20613   

   SexRatio(males per 100 females)  Population_Under5Years  \
0                             94.1                     805   
1                             86.1                     504   
2                            108.2                      96   
3                             95.0                    1936   
4                             90.5                    1306   

   Population_5to9Years  Population_10to14Years  Population_15to19Years  \
0                  1075                     898                     477   
1                   453                     511                     499   
2                   153                     303                     129   
3                  1992                    1837                    1762   
4                  1465                     944                    1217   

   Population_20to24Years  Population_25to34Years  Population_35to44Years  \
0                     578                    2088                    1628   
1                     214                     788                     795   
2                     156                     183                     367   
3                    1376                    3119                    3849   
4                    1128                    2513                    2106   

   Population_45to54Years  Population_55to59Years  Population_60to64Years  \
0                    1200                     886                     683   
1                     968                     612                     561   
2                     430                     296                     260   
3                    3907                    1665                    1323   
4                    2950                    1512                    1472   

   Population_65to74Years  Population_75to84Years  Population_85YearsAndOver  \
0                    1017                     534                        176   
1                     798                     485                        156   
2                     280                     201                         29   
3                    2096                    1106                        364   
4                    2421                    1155                        424   

   MedianAgeInYears  
0              35.5  
1              44.0  
2              47.2  
3              37.7  
4              42.6

Aparentemente o caracter separador aqui é ; e não ,

In [7]:
transactional.head()


Patient Id;Gender;Date of birth;Date of service;Service Id;Lab Id;CodItem;Testing Cost
10210830256-BIO003;F;01/08/1976 00:00:00;2019-0...                                                  0                                     
10210830256-BIO003;F;01/08/1976 00:00:00;2019-0...                                                  0                                     
10210830256-BIO003;F;01/08/1976 00:00:00;2019-0...                                                  0                                     
10210830256-BIO003;F;01/08/1976 00:00:00;2019-0...                                                  0                                     
10210830256-BIO003;F;01/08/1976 00:00:00;2019-0...                                                  0

## Tratamento inicial dos dados

Irei corrigir aqui os primeiros erros que avistei nessa primeira análise. Também vou corrigir alguns tipos de variáveis e verificar dados faltantes

### Ajustando Transactional

In [8]:
transactional = pd.read_csv('transactional_data.csv', sep=';', parse_dates=['Date of birth'],  dayfirst=True)
transactional.head()

Patient Id Gender Date of birth Date of service       Service Id  \
0  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
1  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
2  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
3  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
4  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   

  Lab Id   CodItem Testing Cost  
0   L133  70003237          9,0  
1   L133  70000638         13,0  
2   L133  70001597         49,0  
3   L133  70000103         11,0  
4   L133  70000224         10,0

In [9]:
transactional.dtypes

Patient Id                 object
Gender                     object
Date of birth      datetime64[ns]
Date of service            object
Service Id                 object
Lab Id                     object
CodItem                     int64
Testing Cost               object
dtype: object

In [10]:
transactional['Date of service'] = pd.to_datetime(transactional['Date of service'], format='%Y-%m-%d', errors='coerce')
transactional['Service Id'] = transactional['Service Id'].astype(str)
transactional['Lab Id'] = transactional['Lab Id'].astype(str)
transactional['Testing Cost'] = transactional['Testing Cost'].str.replace(',', '.').astype(np.float64)

In [11]:
transactional.dtypes


Patient Id                 object
Gender                     object
Date of birth      datetime64[ns]
Date of service    datetime64[ns]
Service Id                 object
Lab Id                     object
CodItem                     int64
Testing Cost              float64
dtype: object

In [12]:
transactional.isna().sum()

Patient Id         0
Gender             0
Date of birth      1
Date of service    0
Service Id         0
Lab Id             0
CodItem            0
Testing Cost       0
dtype: int64

Como é só um valor não irá afetar muito a distribuição dos dados

In [13]:
transactional.dropna(inplace=True)
transactional.head()

Patient Id Gender Date of birth Date of service       Service Id  \
0  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
1  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
2  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
3  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
4  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   

  Lab Id   CodItem  Testing Cost  
0   L133  70003237           9.0  
1   L133  70000638          13.0  
2   L133  70001597          49.0  
3   L133  70000103          11.0  
4   L133  70000224          10.0

### Ajustando Geocode

In [14]:
geocode.head()


Unnamed: 0 Lab Id                                            Address  \
0           0   L152      3800 PLEASANT HILL RD STE 1, DULUTH, GA 30096   
1           1   L520                    1614 N JAMES ST, ROME, NY 13440   
2           2   L141     12911 120TH AVE NE STE D60, KIRKLAND, WA 98034   
3           3   L524  5667 PEACHTREE DUNWOODY RD 250, ATLANTA, GA 30342   
4           4   L545                 1204 IL HWY 164, OQUAWKA, IL 61469   

                  Location  Zipcode  
0    34.000319,-84.1629724  30096.0  
1   43.2311327,-75.4445363  13440.0  
2  47.7162786,-122.1838152  98034.0  
3   33.9093875,-84.3529096  30342.0  
4   40.9309925,-90.9437598  61469.0

In [15]:
geocode.dtypes

Unnamed: 0      int64
Lab Id         object
Address        object
Location       object
Zipcode       float64
dtype: object

In [16]:
geocode.drop(columns='Unnamed: 0', inplace=True)
geocode['Zipcode'] = geocode['Zipcode'].astype(str)
geocode.dtypes

Lab Id      object
Address     object
Location    object
Zipcode     object
dtype: object

In [17]:
geocode.isna().sum()

Lab Id      0
Address     0
Location    0
Zipcode     0
dtype: int64

In [18]:
geocode.head()


Lab Id                                            Address  \
0   L152      3800 PLEASANT HILL RD STE 1, DULUTH, GA 30096   
1   L520                    1614 N JAMES ST, ROME, NY 13440   
2   L141     12911 120TH AVE NE STE D60, KIRKLAND, WA 98034   
3   L524  5667 PEACHTREE DUNWOODY RD 250, ATLANTA, GA 30342   
4   L545                 1204 IL HWY 164, OQUAWKA, IL 61469   

                  Location  Zipcode  
0    34.000319,-84.1629724  30096.0  
1   43.2311327,-75.4445363  13440.0  
2  47.7162786,-122.1838152  98034.0  
3   33.9093875,-84.3529096  30342.0  
4   40.9309925,-90.9437598  61469.0

### Ajustando a tabela test

In [19]:
test.head()


CodItem                                          Desc Item Category  \
0  70003237  MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...       CA   
1  70000638                    HEMOGRAMA, AUTOMATIZADO, SANGUE       CA   
2  70001597                                    FERRITINA, SORO       CA   
3  70000103  FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...       CA   
4  70000224  CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...       CA   

    Family     Speciality  Testing Cost  
0  CORELAB   BIOCHEMISTRY          1.78  
1   HEMATO    BLOOD COUNT          2.46  
2  CORELAB  IMMUNOHORMONE          2.11  
3  CORELAB   BIOCHEMISTRY          0.80  
4  CORELAB   BIOCHEMISTRY          1.02

In [20]:
test.dtypes

CodItem           int64
Desc Item        object
Category         object
Family           object
Speciality       object
Testing Cost    float64
dtype: object

CodItem deve ser tratado como string/object nesse contexto

In [21]:
test['CodItem'] = test['CodItem'].astype(str)

In [22]:
test.isna().sum()

CodItem         0
Desc Item       0
Category        0
Family          0
Speciality      0
Testing Cost    0
dtype: int64

In [23]:
test.dtypes

CodItem          object
Desc Item        object
Category         object
Family           object
Speciality       object
Testing Cost    float64
dtype: object

### Ajustando a tabela economic

In [24]:
economic.head()

Unnamed: 0              id Geographic Area Name  \
0           0  8600000US35004          ZCTA5 35004   
1           1  8600000US35005          ZCTA5 35005   
2           2  8600000US35006          ZCTA5 35006   
3           3  8600000US35007          ZCTA5 35007   
4           4  8600000US35010          ZCTA5 35010   

   TotalHouseholds_LessThan$10.000  TotalHouseholds_$10.000to$14.999  \
0                              198                                71   
1                              188                               184   
2                               71                                20   
3                              396                               208   
4                              700                               610   

   TotalHouseholds_$15.000to$24.999  TotalHouseholds_$25.000to$34.999  \
0                               298                               513   
1                               318                               293   
2                               117                               104   
3                               670                               462   
4                              1093                               957   

   TotalHouseholds_$35.000to$49.999  TotalHouseholds_$50.000to$74.999  \
0                               647                              1117   
1                               353                               562   
2                               154                               176   
3                              1173                              1854   
4                              1056                              1512   

   TotalHouseholds_$75.000to$99.999  TotalHouseholds_$100.000to$149.999  \
0                               529                                 945   
1                               299                                 407   
2                               124                                 194   
3                              1578                                2224   
4                               807                                 749   

   TotalHouseholds_$150.000to$199.999  TotalHouseholds_$200.000OrMore  
0                                 245                              61  
1                                  67                              26  
2                                  51                               7  
3                                 473                             254  
4                                 254                             249

In [25]:
economic.drop(columns='Unnamed: 0', inplace=True)

In [26]:
economic.isna().sum()

id                                    0
Geographic Area Name                  0
TotalHouseholds_LessThan$10.000       0
TotalHouseholds_$10.000to$14.999      0
TotalHouseholds_$15.000to$24.999      0
TotalHouseholds_$25.000to$34.999      0
TotalHouseholds_$35.000to$49.999      0
TotalHouseholds_$50.000to$74.999      0
TotalHouseholds_$75.000to$99.999      0
TotalHouseholds_$100.000to$149.999    0
TotalHouseholds_$150.000to$199.999    0
TotalHouseholds_$200.000OrMore        0
dtype: int64

In [27]:
economic.columns

Index(['id', 'Geographic Area Name', 'TotalHouseholds_LessThan$10.000',
       'TotalHouseholds_$10.000to$14.999', 'TotalHouseholds_$15.000to$24.999',
       'TotalHouseholds_$25.000to$34.999', 'TotalHouseholds_$35.000to$49.999',
       'TotalHouseholds_$50.000to$74.999', 'TotalHouseholds_$75.000to$99.999',
       'TotalHouseholds_$100.000to$149.999',
       'TotalHouseholds_$150.000to$199.999', 'TotalHouseholds_$200.000OrMore'],
      dtype='object')

In [28]:
id_vars = ['id', 'Geographic Area Name']

# Colunas que serão derretidas
value_vars = ['TotalHouseholds_LessThan$10.000',
              'TotalHouseholds_$10.000to$14.999',
              'TotalHouseholds_$15.000to$24.999',
              'TotalHouseholds_$25.000to$34.999',
              'TotalHouseholds_$35.000to$49.999',
              'TotalHouseholds_$50.000to$74.999',
              'TotalHouseholds_$75.000to$99.999',
              'TotalHouseholds_$100.000to$149.999',
              'TotalHouseholds_$150.000to$199.999',
              'TotalHouseholds_$200.000OrMore']

# Aplicar a função melt()
tidy_df = pd.melt(economic, id_vars=id_vars, value_vars=value_vars, var_name='Income_Range', value_name='TotalHouseholds')

# Remover a string 'TotalHouseholds_' dos valores em 'Income_Range'
tidy_df['Income_Range'] = tidy_df['Income_Range'].str.replace('TotalHouseholds_', '')

economic = tidy_df
del(tidy_df)

In [29]:
economic.dtypes


id                      object
Geographic Area Name    object
Income_Range            object
TotalHouseholds          int64
dtype: object

Para facilitar mais, posso agrupar pela coluna Geographic Area Name e por Income_Range, para a tabela ser mais eficiente

In [30]:
economic.head()

id Geographic Area Name     Income_Range  TotalHouseholds
0  8600000US35004          ZCTA5 35004  LessThan$10.000              198
1  8600000US35005          ZCTA5 35005  LessThan$10.000              188
2  8600000US35006          ZCTA5 35006  LessThan$10.000               71
3  8600000US35007          ZCTA5 35007  LessThan$10.000              396
4  8600000US35010          ZCTA5 35010  LessThan$10.000              700

Para realizar o agrupamento foi necessário retirar o id, visto que não é uma coluna que possa ser agregada

In [31]:
grouped_economic = economic.drop(columns='id').groupby(['Geographic Area Name', 'Income_Range']).sum().reset_index()
grouped_economic.head()

Geographic Area Name        Income_Range  TotalHouseholds
0          ZCTA5 00601    $10.000to$14.999            15409
1          ZCTA5 00601  $100.000to$149.999              931
2          ZCTA5 00601    $15.000to$24.999            18753
3          ZCTA5 00601  $150.000to$199.999              361
4          ZCTA5 00601      $200.000OrMore               76

### Ajustando demographic

In [32]:
demographic.head()

Unnamed: 0              Id GeographicAreaName  TotalPopulation  \
0           0  8600000US35004        ZCTA5 35004            12045   
1           1  8600000US35005        ZCTA5 35005             7344   
2           2  8600000US35006        ZCTA5 35006             2883   
3           3  8600000US35007        ZCTA5 35007            26332   
4           4  8600000US35010        ZCTA5 35010            20613   

   SexRatio(males per 100 females)  Population_Under5Years  \
0                             94.1                     805   
1                             86.1                     504   
2                            108.2                      96   
3                             95.0                    1936   
4                             90.5                    1306   

   Population_5to9Years  Population_10to14Years  Population_15to19Years  \
0                  1075                     898                     477   
1                   453                     511                     499   
2                   153                     303                     129   
3                  1992                    1837                    1762   
4                  1465                     944                    1217   

   Population_20to24Years  Population_25to34Years  Population_35to44Years  \
0                     578                    2088                    1628   
1                     214                     788                     795   
2                     156                     183                     367   
3                    1376                    3119                    3849   
4                    1128                    2513                    2106   

   Population_45to54Years  Population_55to59Years  Population_60to64Years  \
0                    1200                     886                     683   
1                     968                     612                     561   
2                     430                     296                     260   
3                    3907                    1665                    1323   
4                    2950                    1512                    1472   

   Population_65to74Years  Population_75to84Years  Population_85YearsAndOver  \
0                    1017                     534                        176   
1                     798                     485                        156   
2                     280                     201                         29   
3                    2096                    1106                        364   
4                    2421                    1155                        424   

   MedianAgeInYears  
0              35.5  
1              44.0  
2              47.2  
3              37.7  
4              42.6

In [33]:
demographic.drop(columns='Unnamed: 0', inplace=True)

In [34]:
demographic.isna().sum()

Id                                   0
GeographicAreaName                   0
TotalPopulation                      0
SexRatio(males per 100 females)    500
Population_Under5Years               0
Population_5to9Years                 0
Population_10to14Years               0
Population_15to19Years               0
Population_20to24Years               0
Population_25to34Years               0
Population_35to44Years               0
Population_45to54Years               0
Population_55to59Years               0
Population_60to64Years               0
Population_65to74Years               0
Population_75to84Years               0
Population_85YearsAndOver            0
MedianAgeInYears                   569
dtype: int64

Para fazer o melt de algumas colunas é preciso antes ver se não existe nenhum dado faltante. Neste caso, a coluna SexRatio possui 500 dados faltantes. Uma possível estratégia é substituir com a média ou mediana, no entanto, parece que a distribuição não é gaussiana, ou seja, há uma diferença considerável entre a média e a mediana. Assim, para evitar bagunçar a distribuição, achei melhor apagar as linhas com dados faltantes, já que representam apenas 1,5% do dataset

In [35]:
demographic['SexRatio(males per 100 females)'].describe()

count     32620.000000
mean        116.842275
std        1483.160382
min           0.500000
25%          91.300000
50%          98.400000
75%         107.900000
max      265600.000000
Name: SexRatio(males per 100 females), dtype: float64

In [36]:
demographic['SexRatio(males per 100 females)'].dropna(inplace=True)

Já nesse caso é visível que média e mediana estão muito próximas, então irei substituir os valores faltantes com a média

In [37]:
demographic['MedianAgeInYears'].describe()

count    32551.000000
mean        42.699263
std          9.105954
min          1.900000
25%         37.100000
50%         42.000000
75%         47.600000
max         98.200000
Name: MedianAgeInYears, dtype: float64

In [38]:
demographic['MedianAgeInYears'].fillna(demographic['MedianAgeInYears'].mean(), inplace=True)

Agora podemos seguir com as operações do melt

In [39]:
id_vars = [ 'Id', 'GeographicAreaName']

value_vars = ['TotalPopulation',
              'SexRatio(males per 100 females)',
              'Population_Under5Years',
              'Population_5to9Years',
              'Population_10to14Years',
              'Population_15to19Years',
              'Population_20to24Years',
              'Population_25to34Years',
              'Population_35to44Years',
              'Population_45to54Years',
              'Population_55to59Years',
              'Population_60to64Years',
              'Population_65to74Years',
              'Population_75to84Years',
              'Population_85YearsAndOver',
              'MedianAgeInYears']

tidy_demographic = pd.melt(demographic, id_vars=id_vars, value_vars=value_vars, var_name='Demographic_Category', value_name='Value')

demographic = tidy_demographic
del(tidy_demographic)

In [40]:
demographic.head()

Id GeographicAreaName Demographic_Category    Value
0  8600000US35004        ZCTA5 35004      TotalPopulation  12045.0
1  8600000US35005        ZCTA5 35005      TotalPopulation   7344.0
2  8600000US35006        ZCTA5 35006      TotalPopulation   2883.0
3  8600000US35007        ZCTA5 35007      TotalPopulation  26332.0
4  8600000US35010        ZCTA5 35010      TotalPopulation  20613.0

In [41]:
demographic.dtypes

Id                       object
GeographicAreaName       object
Demographic_Category     object
Value                   float64
dtype: object

Para facilitar a analise, agrupei pelas categorias

In [42]:
grouped_demographic = demographic.drop(columns='Id').groupby(['GeographicAreaName', 'Demographic_Category']).sum().reset_index()
grouped_demographic.head()

GeographicAreaName    Demographic_Category   Value
0        ZCTA5 00601        MedianAgeInYears    41.9
1        ZCTA5 00601  Population_10to14Years  1270.0
2        ZCTA5 00601  Population_15to19Years  1131.0
3        ZCTA5 00601  Population_20to24Years  1140.0
4        ZCTA5 00601  Population_25to34Years  2137.0

## Começando a análise

### Verificando os registros transacionais

A premissa inicial é encontrar três zipcodes mais viáveis para instalação de novas unidades da rede de laboratórios.

Primeiramente, vamos analisar a tabela transactional e observar as tendências de consumo, em relação a idade, gênero e localidade

In [43]:
#criando coluna com idade 

transactional.head()
data_atual = datetime.today().date()
transactional['Age'] = data_atual.year - transactional['Date of birth'].dt.year


In [44]:
transactional.head()

Patient Id Gender Date of birth Date of service       Service Id  \
0  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
1  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
2  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
3  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   
4  10210830256-BIO003      F    1976-08-01      2019-01-07  571904533475-38   

  Lab Id   CodItem  Testing Cost  Age  
0   L133  70003237           9.0   48  
1   L133  70000638          13.0   48  
2   L133  70001597          49.0   48  
3   L133  70000103          11.0   48  
4   L133  70000224          10.0   48

Visualizando consumo com base na idade, seguindo o mesmo range da tabela demographic

In [45]:
# Definir os limites das faixas de idade
age_bins = [0, 5, 10, 15, 20, 25, 35, 45, 55, 60, 65, 75, 85, 120]
age_labels = ['Under 5', '5-9', '10-14', '15-19', '20-24', '25-34', '35-44', '45-54', '55-59', '60-64', '65-74', '75-84', '85 and Over']
# Criar as faixas de idade
transactional['Age Range'] = pd.cut(transactional['Age'], bins=age_bins, labels=age_labels)


Os três primeiros intervalos de idade são os que historicamente mais utilizam os serviços laboratoriais

In [76]:
grouped_cost_age = transactional.groupby('Age Range')['Testing Cost'].sum()
grouped_cost_age = pd.DataFrame(grouped_cost_age)

grouped_cost_age['Testing Cost'] = grouped_cost_age['Testing Cost'].astype(np.float64)

grouped_cost_age = grouped_cost_age.sort_values(by='Testing Cost', ascending=False)
grouped_cost_age['Testing Cost'] = grouped_cost_age['Testing Cost'].map('{:,.2f}'.format)
grouped_cost_age

Testing Cost
Age Range                 
35-44        25,854,237.08
45-54        22,616,765.03
25-34        17,586,118.25
55-59        11,906,721.52
60-64        10,986,132.66
65-74         9,790,503.17
5-9           6,272,986.98
20-24         3,652,070.56
10-14         3,619,808.34
75-84         2,849,922.89
15-19         2,406,891.60
85 and Over   1,479,224.72
Under 5       1,395,824.00

É possível observar que dentre os pacientes que mais consomem, a proporção de mulheres sempre é maior, mais ou menos o dobro

In [80]:
grouped_counts = transactional.groupby('Age Range')['Gender'].value_counts()
grouped_counts = pd.DataFrame(grouped_counts)

grouped_gender_age = grouped_counts.loc[grouped_counts.index.get_level_values('Age Range').isin(['25-34', '35-44', '45-54'])]
grouped_gender_age

count
Age Range Gender        
25-34     F       240951
          M       105863
          I            0
35-44     F       331428
          M       164237
          I            0
45-54     F       301208
          M       165782
          I            0

Abaixo temos os 3 laboratórios com os maiores faturamentos

In [89]:
grouped_lab = pd.DataFrame(transactional.groupby('Lab Id')['Testing Cost'].sum())
grouped_lab = grouped_lab.sort_values(by='Testing Cost', ascending=False)
grouped_lab['Testing Cost'] = grouped_lab['Testing Cost'].map('{:,.2f}'.format)
grouped_lab.iloc[0:3]

Testing Cost
Lab Id              
L133    9,796,639.14
L139    8,851,073.04
L121    6,567,050.54

Localização e Zipcode dos laboratórios de maior faturamento

In [95]:
geocode[geocode['Lab Id'].isin(['L133', 'L139', 'L121'])]

Lab Id                                          Address  \
20   L121     15611 BEL-RED RD SUITE C, BELLEVUE, WA 98008   
81   L139  8100 TIMBERLAKE WAY STE E, SACRAMENTO, CA 95823   
96   L133  2220 GLADSTONE DR. SUITE 7, PITTSBURG, CA 94565   

                  Location  Zipcode  
20  47.632801,-122.1330652  98008.0  
81  38.4634804,-121.416546  95823.0  
96  38.0070008,-121.868574  94565.0

### Procurando Localizações com base em dados econômicos e demográficos

Aqui, vamos buscar as áreas geográficas que mais se aproximam demograficamente e economicamente do nosso público alvo. Que como já definimos, são mulheres entre 25 e 54 anos. Tendo em vista que os grupos entre 35-44 são os com o pico de consumo

In [117]:
filtered_demo = grouped_demographic[grouped_demographic['Demographic_Category'].isin(['Population_25to34Years', 'Population_35to44Years', 
                                                                     'Population_45to54Years', 'SexRatio(males per 100 females)', 'TotalPopulation'])]
filtered_demo

GeographicAreaName             Demographic_Category    Value
4             ZCTA5 00601           Population_25to34Years   2137.0
5             ZCTA5 00601           Population_35to44Years   1925.0
6             ZCTA5 00601           Population_45to54Years   2365.0
14            ZCTA5 00601  SexRatio(males per 100 females)     99.5
15            ZCTA5 00601                  TotalPopulation  17113.0
...                   ...                              ...      ...
529908        ZCTA5 99929           Population_25to34Years    301.0
529909        ZCTA5 99929           Population_35to44Years    223.0
529910        ZCTA5 99929           Population_45to54Years    382.0
529918        ZCTA5 99929  SexRatio(males per 100 females)    118.5
529919        ZCTA5 99929                  TotalPopulation   2502.0

[165600 rows x 3 columns]

Ao analisar as faixas etárias mais significativas em termos de população, é estratégico concentrar o foco, a longo prazo, nas faixas etárias de 25 a 34 anos e de 35 a 44 anos. Isso se justifica pela queda acentuada na população após os 44 anos, o que impacta negativamente o volume de negócios, como visto anteriormente. 

Essa abordagem nos permite capitalizar em dois grupos distintos: o primeiro, entre 35 e 44 anos, responsável pelo maior faturamento; e o segundo, entre 25 e 34 anos, que não apenas contribui significativamente para o faturamento atual, mas também estabelece uma estratégia de longo prazo, aproveitando os três intervalos etários com maior potencial de consumo (25-34, 35-44, 45-54 anos). 

Dito isso, ainda assim o ideal é encontrar uma região que concentre o máximo possível de pessoas que estão dentro do público alvo

In [199]:
top_areas = []

In [200]:
filt_2534 = filtered_demo[filtered_demo.Demographic_Category == 'Population_25to34Years'].sort_values(by='Value', ascending=False)
top5Area_2534 = filt_2534.GeographicAreaName.iloc[0:10].tolist()
top_areas.append(top5Area_2534)
filt_2534.iloc[0:10]


GeographicAreaName    Demographic_Category    Value
45348         ZCTA5 11211  Population_25to34Years  28192.0
331812        ZCTA5 60647  Population_25to34Years  26828.0
331940        ZCTA5 60657  Population_25to34Years  25367.0
331316        ZCTA5 60614  Population_25to34Years  23562.0
331380        ZCTA5 60618  Population_25to34Years  20978.0
331444        ZCTA5 60622  Population_25to34Years  20953.0
46036         ZCTA5 11368  Population_25to34Years  20276.0
99588         ZCTA5 20009  Population_25to34Years  20140.0
45588         ZCTA5 11226  Population_25to34Years  20096.0
45508         ZCTA5 11221  Population_25to34Years  19760.0

In [201]:
filt_3544= filtered_demo[filtered_demo.Demographic_Category == 'Population_35to44Years'].sort_values(by='Value', ascending=False)
top5Area_3544 = filt_3544.GeographicAreaName.iloc[0:10].tolist()
top_areas.append(top5Area_3544)
filt_3544.iloc[0:10]


GeographicAreaName    Demographic_Category    Value
429989        ZCTA5 77494  Population_35to44Years  23166.0
429397        ZCTA5 77449  Population_35to44Years  21261.0
414389        ZCTA5 75070  Population_35to44Years  19131.0
413989        ZCTA5 75034  Population_35to44Years  18751.0
46037         ZCTA5 11368  Population_35to44Years  18627.0
331381        ZCTA5 60618  Population_35to44Years  17100.0
45349         ZCTA5 11211  Population_35to44Years  16378.0
414005        ZCTA5 75035  Population_35to44Years  16328.0
429173        ZCTA5 77433  Population_35to44Years  16310.0
427765        ZCTA5 77084  Population_35to44Years  16232.0

In [202]:
filt_4554= filtered_demo[filtered_demo.Demographic_Category == 'Population_45to54Years'].sort_values(by='Value', ascending=False)
top5Area_4554 = filt_4554.GeographicAreaName.iloc[0:10].tolist()
top_areas.append(top5Area_4554)
filt_4554.iloc[0:10]


GeographicAreaName    Demographic_Category    Value
429990        ZCTA5 77494  Population_45to54Years  18058.0
413990        ZCTA5 75034  Population_45to54Years  17630.0
429398        ZCTA5 77449  Population_45to54Years  17449.0
414390        ZCTA5 75070  Population_45to54Years  16093.0
46214         ZCTA5 11385  Population_45to54Years  14852.0
429814        ZCTA5 77479  Population_45to54Years  14827.0
444646        ZCTA5 79936  Population_45to54Years  14345.0
153366        ZCTA5 30024  Population_45to54Years  14321.0
153558        ZCTA5 30043  Population_45to54Years  14310.0
489846        ZCTA5 92683  Population_45to54Years  14240.0

#### Procurando agora as regiões selecionadas com base no sex ratio, pois estamos em busca de regiões com mais mulheres

Criei uma lista com as top 5 maiores populações de cada intervalo de idade, com o intuito de buscar as regiões que mais conseguem concentrar pessoas do publico alvo




In [204]:
top_areas = [area for rank in top_areas for area in rank]
contagem_valores = pd.Series(top_areas).value_counts()
top5_areas = contagem_valores.index[0:7]
contagem_valores

ZCTA5 11211    2
ZCTA5 11368    2
ZCTA5 75034    2
ZCTA5 75070    2
ZCTA5 77494    2
ZCTA5 77449    2
ZCTA5 60618    2
ZCTA5 60622    1
ZCTA5 77433    1
ZCTA5 30043    1
ZCTA5 30024    1
ZCTA5 79936    1
ZCTA5 77479    1
ZCTA5 11385    1
ZCTA5 77084    1
ZCTA5 75035    1
ZCTA5 20009    1
ZCTA5 60657    1
ZCTA5 60614    1
ZCTA5 60647    1
ZCTA5 11221    1
ZCTA5 11226    1
ZCTA5 92683    1
Name: count, dtype: int64

Os códigos de área: ZCTA5 77449, ZCTA5 75070, ZCTA5 77494, ZCTA5 75034 e ZCTA5 11211 são os mais promissores. 


ZCTA5 77449 - concentra pessoas de 34-45 e 44-55

ZCTA5 75070 - concentra pessoas de 34-45 e 44-55

ZCTA5 77494 - concentra pessoas de 34-45 e 44-55

ZCTA5 75034 - concentra pessoas de 34-45 e 44-55

ZCTA5 11211 - concentra pessoas de 24-35 e 34-45

In [205]:
filtered_demo[(filtered_demo['GeographicAreaName'].isin(top5_areas)) & 
              (filtered_demo['Demographic_Category'] == 'SexRatio(males per 100 females)')
              ].sort_values(by='Value')

GeographicAreaName             Demographic_Category  Value
429406        ZCTA5 77449  SexRatio(males per 100 females)   91.5
414398        ZCTA5 75070  SexRatio(males per 100 females)   91.8
429998        ZCTA5 77494  SexRatio(males per 100 females)   93.7
413998        ZCTA5 75034  SexRatio(males per 100 females)   95.3
45358         ZCTA5 11211  SexRatio(males per 100 females)  100.7
331390        ZCTA5 60618  SexRatio(males per 100 females)  101.2
46046         ZCTA5 11368  SexRatio(males per 100 females)  109.4

As regiões principais selecionadas para avançar na análise são: ZCTA5 77449, ZCTA5 77494, ZCTA5 75034, ZCTA5 75070 e ZCTA5 11211. A última foi especificamente escolhida com base nas informações anteriores, devido à sua capacidade de atrair um público mais jovem, que -além de ser a terceira faixa etária com maior consumo- pode ser convertido em clientes fiéis e representar um bom investimento a longo prazo.

In [236]:
area_names = ['ZCTA5 77449', 'ZCTA5 77494', 'ZCTA5 75034', 'ZCTA5 75070' , 'ZCTA5 11211']

print("Área: ", area_names[0])
grouped_economic[grouped_economic['Geographic Area Name'] == area_names[0]].sort_values(by = 'TotalHouseholds', ascending=False).head()

Área:  ZCTA5 77449


Geographic Area Name        Income_Range  TotalHouseholds
268371          ZCTA5 77449  $100.000to$149.999           165395
268377          ZCTA5 77449    $50.000to$74.999           141322
268378          ZCTA5 77449    $75.000to$99.999           123329
268376          ZCTA5 77449    $35.000to$49.999            81985
268375          ZCTA5 77449    $25.000to$34.999            49324

In [237]:
print("Área: ", area_names[1])

grouped_economic[grouped_economic['Geographic Area Name'] == area_names[1]].sort_values(by = 'TotalHouseholds', ascending=False).head()

Área:  ZCTA5 77494


Geographic Area Name        Income_Range  TotalHouseholds
268744          ZCTA5 77494      $200.000OrMore           189867
268741          ZCTA5 77494  $100.000to$149.999           162982
268743          ZCTA5 77494  $150.000to$199.999           115805
268747          ZCTA5 77494    $50.000to$74.999            65056
268748          ZCTA5 77494    $75.000to$99.999            64885

In [238]:
print("Área: ", area_names[2])
grouped_economic[grouped_economic['Geographic Area Name'] == area_names[2]].sort_values(by = 'TotalHouseholds', ascending=False).head()

Área:  ZCTA5 75034


Geographic Area Name        Income_Range  TotalHouseholds
258744          ZCTA5 75034      $200.000OrMore           167352
258741          ZCTA5 75034  $100.000to$149.999           147022
258743          ZCTA5 75034  $150.000to$199.999           107901
258747          ZCTA5 75034    $50.000to$74.999            89395
258748          ZCTA5 75034    $75.000to$99.999            75734

In [239]:
print("Área: ", area_names[3])
grouped_economic[grouped_economic['Geographic Area Name'] == area_names[3]].sort_values(by = 'TotalHouseholds', ascending=False).head()

Área:  ZCTA5 75070


Geographic Area Name        Income_Range  TotalHouseholds
258991          ZCTA5 75070  $100.000to$149.999           163837
258997          ZCTA5 75070    $50.000to$74.999           102771
258993          ZCTA5 75070  $150.000to$199.999           100225
258994          ZCTA5 75070      $200.000OrMore            98116
258998          ZCTA5 75070    $75.000to$99.999            97983

In [240]:
print("Área: ", area_names[4])
grouped_economic[grouped_economic['Geographic Area Name'] == area_names[4]].sort_values(by = 'TotalHouseholds', ascending=False).head()

Área:  ZCTA5 11211


Geographic Area Name        Income_Range  TotalHouseholds
28344          ZCTA5 11211      $200.000OrMore           133380
28341          ZCTA5 11211  $100.000to$149.999           114817
28343          ZCTA5 11211  $150.000to$199.999            79895
28347          ZCTA5 11211    $50.000to$74.999            75715
28348          ZCTA5 11211    $75.000to$99.999            74955


Usando esta visualização da renda nas áreas, é viável refinar ainda mais as seleções, optando pelas que apresentam a maior concentração de famílias com alta renda.

## Conclusão

A metodologia adotada para esta análise foi fundamentada no histórico de transações, o qual serviu como base para definir um público-alvo segmentado por categorias de idade e gênero. A partir desses critérios demográficos, realizou-se uma análise detalhada visando identificar áreas geográficas que não só concentrassem uma proporção significativa do público-alvo, mas também que apresentassem rendas mais elevadas. Essa abordagem visa maximizar o potencial de atendimento de clientes com maior poder aquisitivo e, consequentemente, aumentar a rentabilidade dos novos laboratórios. Além disso, foi considerado um ponto crucial na análise o fato de que os ZIP CODES selecionados estão localizados em estados diferentes daqueles com maior faturamento da rede (Washington e Califórnia), evitando assim a competição interna e otimizando a expansão da rede de forma estratégica. Dessa maneira, os ZIP CODES selecionados foram:

ZCTA5 11211 - Brooklyn, Nova York

ZCTA5 75034 - Frisco, Texas

ZCTA5 77494 - Katy, Texas